[package]
name = "binary-stream"
version = "3.0.2"
authors = [
  "Mathias Danielsen <mathiasda98@hotmail.com>",
  "Muji <muji@tmpfs.org>"
]
edition = "2021"
description = "Binary stream reader and writer"
repository = "https://github.com/tmpfs/binary-stream"
readme = "README.md"
keywords = ["binary", "reader", "writer"]
license = "MIT"

[features]
wasm32 = []

[dependencies]
thiserror = "1"

[dev-dependencies]
anyhow = "1"
