extend= [
  { path = "coverage_grcov.makefile.toml" }
]
[config]
default_to_workspace = false

[env]
RUST_BACKTRACE = 0
#RUST_LOG = 0
BUILD_TARGET = "${CARGO_MAKE_RUST_TARGET_TRIPLE}"

[tasks.format]
command = "cargo"
args = ["fmt"]

[tasks.format-check]
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.check-current]
command = "cargo"
args = ["check"]

[tasks.check-wasm]
command = "cargo"
args = ["check", "--target", "wasm32-unknown-unknown"]

[tasks.check-android]
command = "cargo"
args = ["check", "--target", "armv7-linux-androideabi"]

[tasks.check]
dependencies = ["check-current", "check-wasm", "check-android"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.docs]
command = "cargo"
args = ["doc", "--open", "--no-deps"]

[tasks.unit]
command = "cargo"
args = ["test", "--lib", "--all-features", "--", "--nocapture"]

[tasks.test]
dependencies = ["unit"]

[tasks.dev]
dependencies = ["test", "format"]

[tasks.doc]
toolchain = "nightly"
command = "cargo"
args = ["doc", "--open", "--no-deps", "--all-features"]

[tasks.clean-coverage]
script = '''
#rm -rf ./target/cover
rm -rf ./target/coverage
rm -f ./target/lcov.info
'''

[tasks.genhtml]
script = '''
grcov . -s . --binary-path ./target/debug -t html --branch --ignore-not-existing -o ./target/coverage/ --ignore 'tests/*' --ignore 'target/*'
'''

[tasks.cover]
alias = "coverage_grcov"

[tasks.coverage]
dependencies = ["clean-coverage", "cover", "genhtml"]
