[config]
default_to_workspace = false
skip_core_tasks = true

[env]
RUST_BACKTRACE = 0
#RUST_LOG = 0
BUILD_TARGET = "${CARGO_MAKE_RUST_TARGET_TRIPLE}"

[tasks.format]
command = "cargo"
args = ["fmt"]

[tasks.format-check]
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.check-current]
command = "cargo"
args = ["check"]

[tasks.check-wasm]
command = "cargo"
args = ["check", "--target", "wasm32-unknown-unknown"]

[tasks.check-android]
command = "cargo"
args = ["check", "--target", "armv7-linux-androideabi"]

[tasks.check]
dependencies = ["check-current", "check-wasm", "check-android"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.doc]
toolchain = "nightly"
command = "cargo"
args = ["doc", "--open", "--no-deps", "--all-features"]

[tasks.unit]
command = "cargo"
args = ["test", "--lib", "--all-features", "--", "--nocapture"]

[tasks.test]
dependencies = ["unit"]

[tasks.dev]
dependencies = ["test", "format"]

[tasks.clean-profraw]
script = '''
rm -f *.profraw
'''

[tasks.clean-coverage]
script = '''
rm -rf ./target/llvm-cov
'''
dependencies = ["clean-profraw"]

[tasks.coverage]
script = '''
cargo llvm-cov clean
cargo llvm-cov test
cargo llvm-cov report --html
'''

[tasks.cover]
dependencies = ["clean-coverage", "coverage", "clean-profraw"]
